### ISSUE TITLE
Configurable features saved to eeprom not persisting through power cycles.

### ISSUE THREAD

**Issue by chase-cobb** [MakeMHz/xbox-hdmi#11]
Open the XboxXDMI app, adjust some of the configurable features (widescreen, luma, etc) and back out of the application. If you restart the application before power cycling the adjustments will still be there, but after a power cycle they are lost.

**Comment by LoveMHz** [comment]
Fixed in version of 2.0.1 of the firmware.

**Comment by chase-cobb** [comment]
Can you leave the ticket open until the firmware is released, for tracking purposes?
