### ISSUE TITLE
To Patch or not to Patch TSOP

### ISSUE THREAD

**Issue by drandreas** [MakeMHz/xbox-hdmi#7]
I'm puzzled by 2 partially conflicting statements

*The Webpage States:*
"A modchip is not required, but heavily recommended as some of the optional features."

*The Installation Manual States:*
"Apply the kernel patches and verify it's activated by running the XboxHDMI application on the Xbox before teardown, as this will fix certain kernel bugs in some games!"

Can I install XboxHDMI without any kernel modifications or is there a chance I will be stuck without a picture and no chance to Flash the TSOP after installing XboxHDMI.

**Comment by dracc** [comment]
You can use xboxhdmi with a stock kernel, but using one with the patches by MakeMHz will most likely provide a better experience as it fixes some minor issues.
Installing the kernel on your tsop is not recommended in case something goes wrong as that is a tad bit harder to recover from than a borked modchip. But if you trust the patched kernel and your tsop flashing skills, you can install the patched kernel on your tsop and it should work as expected.

**Comment by drandreas** [comment]
That clears it up. Thank you.
