### ISSUE TITLE
Kernel patch not compatible with large HDDs

### ISSUE THREAD

**Issue by Nosen92** [MakeMHz/xbox-hdmi#8]
The patch is only compatible with M8+, which by default doesn't support LBA48. This limits the HDD partitions to (I think) 137GB. Larger partitions do not show up.

There is an LBA48 patch for M8+ that is applied using EVtool 1.0.9, however applying that patch first and then the xbox-hdmi patch results in the xbox-hdmi app on the xbox to not recognise the patch as being applied. Applying the xbox-hdmi patch first causes EVtool to not recognise the .bin file as a supported kernel.

As many people have upgraded the harddrive of their xboxes, it's my opinion that this is a rather big problem. If faced with the choice of a bios that supports big HDDs or the xbox-hdmi, I think many will choose the former.

**Comment by LoveMHz** [comment]
m8plus supports LBA48 via the EVtool configuration tool.

> Applying the xbox-hdmi patch first causes EVtool to not recognise the .bin file as a supported kernel.
Can you provide the steps to reproduce?

**Comment by Nosen92** [comment]
Steps to reproduce:

1. Apply the patch using the intructions provided in the guide (using unpack, LIPS and pack).
2. On EVtool, click Open... and try opening the bin file.
3. EVtool casts an error, saying that the bin file is an unsupported kernel.

alternatively:
1. Click Open... and open the m8Plus.bin file.
2. Apply the LBA48 support patch using the bottom left part of the tool. Any partition table option will work.
3. Unpack the bin file.
4. Apply the xbox-hdmi kernel patch with LIPS.
5. Flash this kernel to the Xbox.
6. Open the xbox-hdmi app.
7. It will fail to detect the kernel patch.

**Comment by DarkGabbz** [comment]
I can't reproduce this.

**Comment by Nosen92** [comment]
I've done some further testing.
Seems to me that changing the default dashboard from c:\evoxdash.xbe to e:\Apps\Xbox4Gamers\default.xbe before applying the .ips patch is what breaks the xbox-hdmi app from detecting the patched kernel.

**Comment by DarkGabbz** [comment]
I can't reproduce this either.

**Comment by Nosen92** [comment]
I can record a video of it including all the steps for bug reproduction. Give me a moment.

**Comment by Nosen92** [comment]
Okay this is very strange. It seems to be working fine right now. I'll keep testing

**Comment by Nosen92** [comment]
I fail to reproduce this as well. I must have failed to apply the patch to the right file somehow. Closing the issue.
